export const users = [
    {
        firstName: "Cristian",
        lastName: "Nass",
        email: "cristian@gmail.com",
        city: "Uppsala",
        adress: "some place",
        field: "computer",
        birthAt: 1981,
    },
    {
        firstName: "Erik",
        lastName: "Lundin",
        email: "erik@gmail.com",
        city: "Uppsala",
        adress: "granby",
        field: "computer",
        birthAt: 1980,
    },
    {
        firstName: "Stam",
        lastName: "Kurjan",
        email: "stam@yahoo.com",
        city: "Uppsala",
        adress: "folhagen",
        field: "computer",
        birthAt: 1990,
    },
    {
        firstName: "Jack",
        lastName: "Daniel",
        email: "jack@yahoo.com",
        city: "Stockholm",
        adress: "granby",
        field: "music",
        birthAt: 1995,
    },
    {
        firstName: "Sara",
        lastName: "Kashani",
        email: "sara@yahoo.com",
        city: "Tehran",
        adress: "elahiye",
        field: "fashion",
        birthAt: 1993,
    },
    {
        firstName: "Sofia",
        lastName: "Erikson",
        email: "sofi@yahoo.com",
        city: "Malmo",
        adress: "Gottsunda",
        field: "art",
        birthAt: 1993,
    },
    {
        firstName: "Sara",
        lastName: "Kermani",
        email: "kermani@yahoo.com",
        city: "Tehran",
        adress: "elahiye",
        field: "chemistry",
        birthAt: 1986,
    },
    {
        firstName: "Johan",
        lastName: "Lindau",
        email: "johan@knowit.se",
        city: "Uppsala",
        adress: "sunersta",
        field: "projrct leader",
        birthAt: 1976,
    },
];