export const users = [
    {
        id: 1,
        firstName: "Cristian",
        lastName: "Nass",
        email: "cristian@gmail.com",
        phone: '0762931896',
        city: "Uppsala",
        adress: "some place",
        field: "computer",
        birthAt: 1981
    },
    {
        id: 2,
        firstName: "Erik",
        lastName: "Lundin",
        email: "erik@gmail.com",
        phone: '0762931800',
        city: "Uppsala",
        adress: "granby",
        field: "computer",
        birthAt: 1980,
    },
    {
        id: 3,
        firstName: "Stam",
        lastName: "Kurjan",
        email: "stam@yahoo.com",
        phone: '0762931801',
        city: "Uppsala",
        adress: "folhagen",
        field: "computer",
        birthAt: 1990,
    },
    {
        id: 4,
        firstName: "Jack",
        lastName: "Daniel",
        email: "jack@yahoo.com",
        phone: '0762931701',
        city: "Stockholm",
        adress: "granby",
        field: "music",
        birthAt: 1995,
    },
    {
        id: 5,
        firstName: "Sara",
        lastName: "Kashani",
        email: "sara@yahoo.com",
        phone: '0762231701',
        city: "Tehran",
        adress: "elahiye",
        field: "fashion",
        birthAt: 1993,
    },
    {
        id: 6,
        firstName: "Sofia",
        lastName: "Erikson",
        email: "sofi@yahoo.com",
        city: "Malmo",
        phone: '0722231701',
        adress: "Gottsunda",
        field: "art",
        birthAt: 1993,
    },
    {
        id: 7,
        firstName: "Sara",
        lastName: "Kermani",
        email: "kermani@yahoo.com",
        city: "Tehran",
        phone: '0722231710',
        adress: "elahiye",
        field: "chemistry",
        birthAt: 1986,
    },
    {
        id: 8,
        firstName: "Johan",
        lastName: "Lindau",
        email: "johan@knowit.se",
        city: "Uppsala",
        phone: '0722631710',
        adress: "sunersta",
        field: "projrct leader",
        birthAt: 1976,
    },
];